'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import styles from './dashboard.module.css'
import { getReports, getUserId, type Report } from '@/lib/api'

export default function Dashboard() {
  const [reports, setReports] = useState<Report[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    async function fetchReports() {
      try {
        const userId = getUserId()
        console.log('Fetching reports for user:', userId)
        
        const response = await getReports(userId)
        setReports(response.reports)
        setLoading(false)
      } catch (err) {
        console.error('Error fetching reports:', err)
        setError('Failed to load reports')
        setLoading(false)
      }
    }

    fetchReports()
  }, [])

  return (
    <main className={styles.main}>
      <div className={styles.container}>
        <h1 className={styles.title}>Progress Dashboard</h1>
        <p className={styles.subtitle}>AI-powered insights and reports</p>
        
        {loading && (
          <div className={styles.placeholder}>
            <p>Loading your reports...</p>
          </div>
        )}

        {error && (
          <div className={styles.placeholder}>
            <p style={{ color: '#ff6b6b' }}>{error}</p>
          </div>
        )}

        {!loading && !error && reports.length === 0 && (
          <div className={styles.placeholder}>
            <p>No reports yet!</p>
            <p>Complete a game session to see your AI-generated progress report here.</p>
            <p style={{ fontSize: '0.875rem', color: '#aaa', marginTop: '1rem' }}>
              Reports are generated automatically after each session and will appear here within 30 seconds.
            </p>
          </div>
        )}

        {!loading && !error && reports.length > 0 && (
          <div className={styles.reportsContainer}>
            <p style={{ marginBottom: '1.5rem', color: '#aaa' }}>
              Found {reports.length} report{reports.length !== 1 ? 's' : ''}
            </p>
            
            {reports.map((report) => (
              <div key={report.sessionId} className={styles.reportCard}>
                <div className={styles.reportHeader}>
                  <h3>Session Report</h3>
                  <span className={styles.reportDate}>
                    {new Date(report.timestamp).toLocaleString()}
                  </span>
                </div>
                <div className={styles.reportContent}>
                  <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit' }}>
                    {report.report}
                  </pre>
                </div>
                <div className={styles.reportFooter}>
                  <span>Generated by {report.modelUsed}</span>
                  <span>Session ID: {report.sessionId}</span>
                </div>
              </div>
            ))}
          </div>
        )}

        <Link href="/" className={styles.backButton}>
          Back to Home
        </Link>
      </div>
    </main>
  )
}
